import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import MiniSearch from "minisearch";
import { processTerm, tokenize } from "../src/rag/tokenize";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE_DIR = path.join(ROOT, "corpus", "src");
const OUTPUT_DIR = path.join(ROOT, "public", "corpus");

type Kind = "resume" | "paper" | "repo" | "profile" | "project";

interface Section {
  heading: string;
  text: string;
}

interface Doc {
  id: string;
  title: string;
  kind: Kind;
  lang: "en" | "zh";
  url?: string;
  date?: string;
  sections: Section[];
}

interface Chunk {
  id: string;
  docId: string;
  docTitle: string;
  heading: string;
  kind: Kind;
  lang: "en" | "zh";
  url?: string;
  date?: string;
  text: string;
}

function splitSections(body: string): Section[] {
  const sections: Section[] = [];
  let heading = "摘要";
  let lines: string[] = [];

  const flush = () => {
    const text = lines.join("\n").trim();
    if (text) sections.push({ heading, text });
    lines = [];
  };

  for (const line of body.split("\n")) {
    const match = /^#{2,3}\s+(.+)$/.exec(line);
    if (match) {
      flush();
      heading = match[1]!.trim();
    } else {
      lines.push(line);
    }
  }
  flush();
  return sections;
}

function readDocs(): { docs: Doc[]; hashes: Record<string, string> } {
  if (!fs.existsSync(SOURCE_DIR)) {
    throw new Error(`Missing corpus source directory: ${SOURCE_DIR}`);
  }

  const hashes: Record<string, string> = {};
  const docs = fs
    .readdirSync(SOURCE_DIR)
    .filter((name) => name.endsWith(".md"))
    .sort()
    .map((name): Doc => {
      const file = path.join(SOURCE_DIR, name);
      const raw = fs.readFileSync(file, "utf8");
      hashes[path.relative(ROOT, file)] = createHash("sha256")
        .update(raw)
        .digest("hex")
        .slice(0, 16);

      const { data, content } = matter(raw);
      const lang = /[\u3400-\u9fff]/u.test(content) ? "zh" : "en";
      return {
        id: `about-${name.replace(/\.md$/, "")}`,
        title: typeof data.title === "string" ? data.title : name,
        kind: (typeof data.kind === "string" ? data.kind : "profile") as Kind,
        lang,
        url: typeof data.url === "string" ? data.url : undefined,
        date: typeof data.date === "string" ? data.date : undefined,
        sections: splitSections(content),
      };
    });

  return { docs, hashes };
}

function packParagraphs(paragraphs: string[], target = 750): string[] {
  const chunks: string[] = [];
  let current = "";
  for (const paragraph of paragraphs) {
    if (current && current.length + paragraph.length + 2 > target) {
      chunks.push(current);
      current = paragraph;
    } else {
      current = current ? `${current}\n\n${paragraph}` : paragraph;
    }
  }
  if (current) chunks.push(current);
  return chunks;
}

function chunkDocs(docs: Doc[]): Chunk[] {
  return docs.flatMap((doc) => {
    let index = 0;
    return doc.sections.flatMap((section) =>
      packParagraphs(section.text.split(/\n{2,}/).map((text) => text.trim()).filter(Boolean))
        .map((text) => ({
          id: `${doc.id}#${index++}`,
          docId: doc.id,
          docTitle: doc.title,
          heading: section.heading,
          kind: doc.kind,
          lang: doc.lang,
          url: doc.url,
          date: doc.date,
          text,
        })),
    );
  });
}

function writeKeywords(): void {
  const keywords = [
    "Python",
    "C++",
    "Java",
    "Go",
    "TypeScript",
    "LLM 应用",
    "Coding Agent",
    "ReAct",
    "Plan Mode",
    "MCP",
    "Planner-Executor",
    "SQL 安全",
    "MinIO",
    "MySQL",
    "异步任务",
    "跨会话记忆",
    "工业视觉",
    "目标检测",
    "姿态识别",
    "模型预测控制",
    "IoT",
  ];

  fs.writeFileSync(
    path.join(ROOT, "src", "ui", "keywords.generated.ts"),
    [
      "/* Generated by scripts/build-corpus.ts from the approved public profile. */",
      "",
      "export const RESUME_KEYWORDS = [",
      ...keywords.map((keyword) => `  ${JSON.stringify(keyword)},`),
      "] as const;",
      "",
    ].join("\n"),
    "utf8",
  );
}

function main(): void {
  const { docs, hashes } = readDocs();
  const chunks = chunkDocs(docs);

  const index = new MiniSearch<Chunk>({
    idField: "id",
    fields: ["text", "heading", "docTitle"],
    storeFields: ["docId", "docTitle", "heading", "kind", "lang", "url", "date"],
    tokenize,
    processTerm,
  });
  index.addAll(chunks);

  fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(path.join(OUTPUT_DIR, "docs"), { recursive: true });

  const manifest = docs.map((doc) => ({
    id: doc.id,
    title: doc.title,
    kind: doc.kind,
    lang: doc.lang,
    url: doc.url,
    date: doc.date,
    sections: doc.sections.map((section) => section.heading),
    chunks: chunks.filter((chunk) => chunk.docId === doc.id).length,
  }));

  const bundle = {
    version: 1,
    builtAt: new Date().toISOString().slice(0, 10),
    docs: manifest,
    chunks: Object.fromEntries(chunks.map((chunk) => [chunk.id, chunk.text])),
    index: index.toJSON(),
  };

  fs.writeFileSync(path.join(OUTPUT_DIR, "index.json"), JSON.stringify(bundle), "utf8");
  for (const doc of docs) {
    fs.writeFileSync(
      path.join(OUTPUT_DIR, "docs", `${doc.id}.json`),
      JSON.stringify(doc),
      "utf8",
    );
  }

  writeKeywords();
  fs.writeFileSync(
    path.join(ROOT, "corpus.lock.json"),
    JSON.stringify({ builtAt: bundle.builtAt, sources: hashes }, null, 2),
    "utf8",
  );

  const kb = fs.statSync(path.join(OUTPUT_DIR, "index.json")).size / 1024;
  console.log(`Built ${docs.length} documents and ${chunks.length} chunks (${kb.toFixed(0)} KB).`);
}

main();
